springdoc:
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /docs
    operationsSorter: method
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework: INFO

server:
  port: ${port:8080}

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/changelog/master-changelog.xml
    enabled: true
